<?php

$xpdo_meta_map = array (
  'xPDOObject' => 
  array (
    0 => 'Blog',
    1 => 'BlogUser',
    2 => 'Comment',
    3 => 'CommentOnline',
    4 => 'Favourite',
    5 => 'FavouriteTag',
    6 => 'Friend',
    7 => 'GeoTarget',
    8 => 'Invite',
    9 => 'NotifyTask',
    10 => 'Reminder',
    11 => 'Session',
    12 => 'StreamSubscribe',
    13 => 'StreamUserType',
    14 => 'Talk',
    15 => 'TalkBlacklist',
    16 => 'TalkUser',
    17 => 'Topic',
    18 => 'TopicContent',
    19 => 'TopicQuestionVote',
    20 => 'TopicRead',
    21 => 'TopicTag',
    22 => 'User',
    23 => 'UserAdministrator',
    24 => 'UserFieldValue',
    25 => 'UserfeedSubscribe',
    26 => 'Vote',
  ),
  'xPDOSimpleObject' => 
  array (
    0 => 'GeoCity',
    1 => 'GeoCountry',
    2 => 'GeoRegion',
    3 => 'StreamEvent',
    4 => 'Subscribe',
    5 => 'TopicPhoto',
    6 => 'UserChangemail',
    7 => 'UserField',
    8 => 'UserNote',
    9 => 'Wall',
  ),
);